openapi: "3.0.0"
info:
  title: Bot App Service
  version: 1.0.0
paths:
  /app/index:
    get:
      summary: Greet a person
      description: Greet a person by name
      tags:
        - greeting
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
      deprecated: false
      security: []
  /greeter/greet:
    get:
      summary: Say hello
      description: Says hello to world
      tags:
        - greeting
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
      deprecated: false
      security: []